language: php
php:
  - '7.0'
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
  irc:
    channel:
      - "irc.tuxfamily.org#Libertempo"
    on_success: never # default: change
    on_failure: always # default: always
script: vendor/bin/atoum

after_script:
  - php Vendor/Bin/codacycoverage clover clover.xml
